### ISSUE TITLE
Assert::all* not handle

### ISSUE THREAD

**Issue by soullivaneuh** [phpstan/phpstan-webmozart-assert#10]
If I do:

```php
$opLimit = $input->getOption('operation-limit');
$timeLimit = $input->getOption('time-limit');
Assert::numeric($opLimit);
Assert::numeric($timeLimit);
$opLimit = (int) $opLimit;
$timeLimit = (int) $timeLimit;
```

No error outputted. But if I do:

```php
$opLimit = $input->getOption('operation-limit');
$timeLimit = $input->getOption('time-limit');
Assert::allNumeric($opLimit, $timeLimit);
$opLimit = (int) $opLimit;
$timeLimit = (int) $timeLimit;
```

I have:

```
src/AppBundle/Command/OperationExecuteCommand.php:105:Cannot cast array<string>|bool|string|null to int.
src/AppBundle/Command/OperationExecuteCommand.php:106:Cannot cast array<string>|bool|string|null to int.
```

It seems the `all*` methods are ignored by the plugin.

**Comment by ondrejmirtes** [comment]
`::all` asserts are implemented. They do something else than you probably think. [According to documentation](https://github.com/webmozart/assert#collection-assertions), they are meant to be used by arrays and traversables:

> All of the above assertions can be prefixed with all*() to test the contents of an array or a \Traversable

**Comment by soullivaneuh** [comment]
Oh right, my bad then. Sorry for that.
