### ISSUE TITLE
Support for assertions resulting in non-empty string

### ISSUE THREAD

**Issue by villfa** [phpstan/phpstan-webmozart-assert#129]
See discussion in #128

**Comment by herndlm** [comment]
This should be possible to do now thx to https://github.com/phpstan/phpstan-src/pull/1254 which also solved a couple of other problems. See https://github.com/phpstan/phpstan-src/pull/1068 where something similar was done in phpstan itself. I think we should use the same approach here too.
I can take a look at it soon. Or you go ahead if you like :) Just make sure the all* assertions are working fine too, I had to fix something there recently.
