### ISSUE TITLE
Add FQCN support in Assert::implementsInterface

### ISSUE THREAD

**Issue by karser** [phpstan/phpstan-webmozart-assert#17]
The function [implementsInterface($value, $interface, $message = '')](https://github.com/webmozart/assert/blob/1.5.0/src/Assert.php#L1336) from the [docs](https://github.com/webmozart/assert)
>Check that a class implements an interface.

Here is the code:
```
<?php declare(strict_types=1);

namespace App;

use DateTimeInterface;
use Webmozart\Assert\Assert;

Assert::implementsInterface(\DateTime::class, DateTimeInterface::class);
Assert::implementsInterface(\DateTimeZone::class, DateTimeInterface::class);
```

Here is phpstan error:
```
Call to static method Webmozart\Assert\Assert::implementsInterface() with 'DateTime' and 'DateTimeInterface' will always evaluate to false.      
Call to static method Webmozart\Assert\Assert::implementsInterface() with 'DateTimeZone' and 'DateTimeInterface' will always evaluate to false.  
```

**Comment by mamazu** [comment]
The error is not with the FQN, the problem is that the phpstan implementation is interpreting the first parameter as an object and checks if implements the interface and comes to the conclusion that the string "DateTime" never implements a DateTimeInterface. This should be fixed by #16 .
