### ISSUE TITLE
`Assert::implementsInterface($foo, <Type>)` is incorrectly being translated to `assert($foo instanceof <Type>)`

### ISSUE THREAD

**Issue by Ocramius** [phpstan/phpstan-webmozart-assert#18]
`Assert::implementsInterface()` works on `object|string`, not just `object`, so it should be translated to something like `assert($foo instanceof $type || in_array($interface, \class_implements($value)))` (see https://3v4l.org/VdIbR).

Not sure what the correct translation (understood by PHPStan) would be.

For reference, this is the current implementation:

https://github.com/phpstan/phpstan-webmozart-assert/blob/97cde39e6ddb70915e7188704d0ebd174f07b688/src/Type/WebMozartAssert/AssertTypeSpecifyingExtension.php#L303-L313

**Comment by ondrejmirtes** [comment]
Can you tell me some real-world examples of implementsInterface usages? I've seen examples where both arguments are literal strings which doesn't seem very useful.

**Comment by Ocramius** [comment]
Currently finding it in something like:

```php
class MyThingFactory
{
    public function make(string $thing)
    {
        Assert::implementsInterface($thing, SomeDto::class);

        // use $thing static API here
    }
}

**Comment by Ocramius** [comment]
Note that this is completely removable if I use something like:

```php
class MyThingFactory
{
    /**
     * @template T of SomeDto
     * @param class-string<T> $thing
     */
    public function make(string $thing)
    {
        Assert::implementsInterface($thing, SomeDto::class);

        // use $thing static API here
    }
}
```

Not sure if that's understood by the tooling yet though

**Comment by orklah** [comment]
> Can you tell me some real-world examples of implementsInterface usages? I've seen examples where both arguments are literal strings which doesn't seem very useful.

This leads to weird hacks in real projects:
https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlock/StandardTagFactory.php#L177
