### ISSUE TITLE
Add support for Assert::oneOf()

### ISSUE THREAD

**Issue by greg0ire** [phpstan/phpstan-webmozart-assert#24]
Now that we can [narrow types](https://phpstan.org/writing-php-code/phpdoc-types#literals-and-constants), it would be quite handy to be able to do this:

```diff 
     /**
      * @var string
      * @phpstan-var EntityType::TYPE_*
      */
     private $inputType;
 
     public function __construct(string $inputType)
     {
         Assert::oneOf($inputType, EntityType::ALL);

-        assert(in_array($inputType, EntityType::ALL, true));
         $this->inputType = $inputType;
 
     }
```

**Comment by ondrejmirtes** [comment]
What about:

```php
/**
 * @param EntityType::TYPE_* $inputType
 */
public function __construct(string $inputType)
{
}
```

?

**Comment by ondrejmirtes** [comment]
It'd have the benefit to point out dangerous calls to the constructor...

**Comment by greg0ire** [comment]
But then the `Assert` would be useless wouldn't it? And there are dangerous calls, I want to catch them here, because I'm parsing a config file, and I want to catch mistakes (so my constructor can be called with invalid data, and phpstan will bring no benefit because it can't spot issues in a YAML file)

**Comment by ondrejmirtes** [comment]
PHPStan currently doesn't understand `Assert::oneOf`. Once it does, it will mark it as "always true", which happens only with "strict-rules" installed. You should add the PHPDoc above the constructor anyway. So this is a non-issue for most people.

If you don't want to see the "always true" warning with this check even if you want to use strict-rules, you can change the `treatPhpDocTypesAsCertain` setting: https://phpstan.org/config-reference#treatphpdoctypesascertain

**Comment by greg0ire** [comment]
Indeed I think I am in an edge case here :thinking: thanks for your help!
