### ISSUE TITLE
Add support for Assert::methodExists

### ISSUE THREAD

**Issue by alexander-schranz** [phpstan/phpstan-webmozart-assert#30]
I'm trying to check if a method exist on a third party library using Assert::methodExists

```php
$response = $this->client->request(
    'GET',
    $this->getUrl($module, $id, $subModule, $subId),
    $this->defaultOptions,
);

Assert::same(200, $response->getStatusCode());

// not every client is stream able so we need to check if its possible to stream the content
Assert::methodExists($response, 'toStream');

$response->toStream();
```

But this currently fails with:

> Call to an undefined method Symfony\Contracts\HttpClient\ResponseInterface::toStream()

Playground looks like this (Assert is not possible there maybe it could be added):

https://phpstan.org/r/130e8b7a-7b51-460f-b884-6a532ae935c6

Would be nice if `Assert::methodExists` could also be supported by phpstan.

**Comment by ondrejmirtes** [comment]
Hi, this is trivial to implement, see how the extension works: https://github.com/phpstan/phpstan-webmozart-assert/blob/master/src/Type/WebMozartAssert/AssertTypeSpecifyingExtension.php
