### ISSUE TITLE
Assert::allIsInstanceOf evaluates to non iterables

### ISSUE THREAD

**Issue by herndlm** [phpstan/phpstan-webmozart-assert#35]
Having something like
```php
final class PhpStanTest
{
    /**
     * @return stdClass[]
     */
    public function foo(bool $bar): array
    {
        $result = $bar ? [new stdClass(), new stdClass()] : false;

        Assert::allIsInstanceOf($result, stdClass::class);

        return $result;
    }
}
```
falsely reports
```
Method PhpStanTest::foo() should return array<stdClass> but returns array<int, stdClass>|false.
```

It cannot be false though because the `all*` methods are internally checking for iterables in https://github.com/webmozarts/assert/blob/master/src/Assert.php#L1947

I would love to help out here but do not know yet where to start. Feel free to point me there or to any starter resources if you like :)

**Comment by herndlm** [comment]
What I found out so far:
- `AssertTypeSpecifyingExtension::arrayOrIterable` is called where
- `TypeUtils::getArrays($currentType)` returns an empty array which leads to the `elseif` clause where
- `(new IterableType(new MixedType(), new MixedType()))->isSuperTypeOf($currentType)->yes()` is returning `false` (the trinary internally is set to maybe) which leads to
- `return new SpecifiedTypes([], []);`

`$currentType` is
<img width="441" alt="image" src="https://user-images.githubusercontent.com/5738896/105388591-1f0ed100-5c17-11eb-8f0c-bf8428ef9a86.png">

I guess it should enter the `elseif` where it would create an iterable type and I also guess the `ConstantBooleanType` should not even be there or be ignored because of `all*` internals or so.

To be continued hopefully..

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan-webmozart-assert/commit/dcb38393a99d4562bd21137ecb179c43dff3fd70
