### ISSUE TITLE
Since 0.12.9: `expects array<string>, iterable<string> given`

### ISSUE THREAD

**Issue by ruudk** [phpstan/phpstan-webmozart-assert#36]
Not sure if this is an issue or not, and if it's related to phpstan-webmozart-assert or just webmozart-assert.

When upgrading from 0.12.8 to 0.12.9 I get this error:
```
Parameter #1 $input of class Command constructor expects array<string>, iterable<string> given.
```

This is coming from:
```php
$input = $request->request->get('input');

Assert::isList($input);
Assert::allString($input);

$command = new Command($input)
```

My `Command` has the following constructor:
```php
/**
* @param string[] $input
*/
public function __construct(array $input)
```

Assert's `allString` method defines:
```
    /**
     * @psalm-pure
     * @psalm-assert iterable<string> $value
     *
     * @param mixed  $value
     * @param string $message
     *
     * @throws InvalidArgumentException
     */
    public static function allString($value, $message = '');
```

It seems that PHPStan no longer accepts passing an `iterable<string>`  into a `string[]`.

**Comment by ondrejmirtes** [comment]
This is actually a feature request for `isList` assert to be supported. Implemented: https://github.com/phpstan/phpstan-webmozart-assert/commit/7c19228cf2077b9bb6ac509476d02550eccaf1d2

**Comment by ondrejmirtes** [comment]
0.12.10 released.

**Comment by ruudk** [comment]
@ondrejmirtes Amazing, thank you!! 💙
