### ISSUE TITLE
Assert::keyExists() should be supported

### ISSUE THREAD

**Issue by clxmstaab** [phpstan/phpstan-webmozart-assert#39]
with this plugin, phpstan should be aware about the array shape of the variable involved:

```
/**
 * @param array{password: mixed, email: mixed} $arr
 */
function a($arr) {
}

$data = $_POST;

Assert::keyExists($data, 'password');
Assert::keyExists($data, 'email');

a($data);

```

it would be even better if we could verify that the keys are of a certain type, e.g. string in my above example.
though it seems this is not even possible with `Assert` itself, without additional asserts.

**Comment by ondrejmirtes** [comment]
Hi, this is trivial to implement, see for example a similar assert: https://github.com/phpstan/phpstan-webmozart-assert/commit/7c19228cf2077b9bb6ac509476d02550eccaf1d2

I'm sure you'll figure out how to send a PR with `Assert::keyExists` support.

**Comment by villfa** [comment]
I just take a look at this issue and here what I've found:
* `keyExists` is supported since 0.12.5: https://github.com/phpstan/phpstan-webmozart-assert/commit/3920d37aa7abd66cbb9e3248934a842bf2a164e7
* there is still an error with the code snippet given by OP: ` Parameter #1 $arr of function a expects array{password: mixed, email: mixed}, array<string, mixed> given.`
* Using directly `array_key_exists` works: https://phpstan.org/r/29521210-c991-48c4-9ad2-5e150a2c4c59

**Comment by herndlm** [comment]
@clxmstaab do you know if this is still relevant? See the previous comment.
I know that we use it successfully to safely access array offsets but I think not to define array shapes like in your example.

**Comment by clxmstaab** [comment]
@herndlm since the initially reported problem is still present (per villfa), I am not sure what you are asking for?

**Comment by herndlm** [comment]
@clxmstaab I was sure the linked phpstan story was closed, just realized it's still open. Sorry for the noise 😓

Not sure how related the keyExists from here is though, or if it has a connection to the problem that you found. In general it is supported already.
Looks like in the phpstan story the problematic part is the manual setting of the token via `$data['token'] = $_POST['token'];`. But that should be discussed over there I guess. 

I was just not sure if there is still something to do here. And I'm still not :)

**Comment by ondrejmirtes** [comment]
Similar feature was just contributed to beberlei-assert: https://github.com/phpstan/phpstan-beberlei-assert/pull/37

**Comment by herndlm** [comment]
> Similar feature was just contributed to beberlei-assert: [phpstan/phpstan-beberlei-assert#37](https://github.com/phpstan/phpstan-beberlei-assert/pull/37)

We support those 2 already, see https://github.com/phpstan/phpstan-webmozart-assert/blob/1.0.9/tests/Type/WebMozartAssert/data/array.php#L13 and next block. Which is why I was confused by this issue as the last comments show :)

**Comment by villfa** [comment]
The issue should be renamed to avoid such confusion.

**Comment by ondrejmirtes** [comment]
Oh, I know - this is basically https://github.com/phpstan/phpstan/issues/6552. Closing this one.
