### ISSUE TITLE
After upgrading PHPStan from `0.12.82` to `0.12.83`: `Assert::notNull($object->getEvent())` no longer removes nullability

### ISSUE THREAD

**Issue by ruudk** [phpstan/phpstan-webmozart-assert#44]
This code used to work fine, until I upgraded from `0.12.82` to `0.12.83`
```php
class Draft {
    public function getEvent(): ?Event {}
}

class Listing {
    public function setEvent(Event $event): void {}
}

private function createListing(Draft $draft) : Listing
{
    Assert::notNull($draft->getEvent());

    $listing = new Listing();
 
    // Parameter #1 $event of method Listing::setEvent() expects Event, Event|null given.
    $listing->setEvent($draft->getEvent());

    return $listing;
}
```

Tried to reproduce it but I cannot: https://phpstan.org/r/c0ef8412-208b-441d-95c5-e3a9df165e55

**Comment by ondrejmirtes** [comment]
Hi, this is definitely happening because you're using bleedingEdge, this is a preview how 1.0 is going to behave.

There's an article about this: https://phpstan.org/blog/remembering-and-forgetting-returned-values

Your solution is to store event into a variable right after the assert.

**Comment by ondrejmirtes** [comment]
This is what's probably going on in your original code: https://phpstan.org/r/22970d69-43e2-4607-9d82-cbaf6e5c884c

**Comment by ruudk** [comment]
Got it, makes sense! Thanks.
