### ISSUE TITLE
Internal type conversion from array to iterable.

### ISSUE THREAD

**Issue by waltertamboer** [phpstan/phpstan-webmozart-assert#46]
After updating my dependencies I'm experiencing problems with analysis. Array types seem to be converted internally to iterable types when calling webmozart/assert methods. I've added screenshots and my system information. Hopefully this helps, if you need more information, ping me :-)

```
class Logic
{
    /**
     * @param array<int, array<string, mixed>> $items
     */
    public function execute(array $items): void
    {
        \Webmozart\Assert\Assert::allKeyExists($items, 'id');

        // ...

        $this->executeSomethingElse($items); // ERROR: Now phpstan says that $items has become an iterable.
    }

    /**
     * @param array<int, array<string, mixed>> $items
     */
    public function executeSomethingElse(array $items): void
    {
    }
}
```

![image](https://user-images.githubusercontent.com/508054/115875960-0e543e00-a446-11eb-8259-ad5e06df087e.png)

System information:

```
bash-5.1$ php -v
PHP 7.4.16 (cli) (built: Mar 25 2021 23:24:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
```

![image](https://user-images.githubusercontent.com/508054/115876311-7014a800-a446-11eb-98e8-0c63c94e036e.png)

**Comment by waltertamboer** [comment]
I do notice that the typehint of allKeyExists is an iterable:

```
    /**
     * @psalm-pure
     *
     * @param iterable<array> $array
     * @param string|int      $key
     * @param string          $message
     *
     * @throws InvalidArgumentException
     *
     * @return void
     */
    public static function allKeyExists($array, $key, $message = '')
    {
        static::__callStatic('allKeyExists', array($array, $key, $message));
    }
```

Does that cause phpstan to think the variable is an array?

**Comment by ondrejmirtes** [comment]
The bug will be somewhere in this method:

> https://github.com/phpstan/phpstan-webmozart-assert/blob/5d9128174c62ff840e3ee488a0ad04d6705bc36d/src/Type/WebMozartAssert/AssertTypeSpecifyingExtension.php#L441-L476

You can take advantage of [this guide](https://phpstan.org/developing-extensions/testing#type-inference) and submit a failing test, thanks.

**Comment by herndlm** [comment]
Fyi the current state looks like the following
```php
	public function allKeyExists(array $array, iterable $iterable): void
	{
		\PHPStan\Testing\assertType('array', $array);
		Assert::allKeyExists($array, 'id');
		\PHPStan\Testing\assertType('array<array&hasOffset(\'id\')>', $array);
		Assert::allKeyExists($array, 'name');
		\PHPStan\Testing\assertType('array<array&hasOffset(\'id\')&hasOffset(\'name\')>', $array);

		\PHPStan\Testing\assertType('iterable', $iterable);
		Assert::allKeyExists($iterable, 'id');
		\PHPStan\Testing\assertType('iterable<array&hasOffset(\'id\')>', $iterable);
		Assert::allKeyExists($iterable, 'name');
		\PHPStan\Testing\assertType('iterable<array&hasOffset(\'id\')&hasOffset(\'name\')>', $iterable);
	}
```

No iterable for the array input any more, so maybe this has been fixed? The array shape has a format not known to me though. Is this expected?
I can add this or an adapted version to the tests if that makes sense
