### ISSUE TITLE
Assert::length() should result in non-empty-string

### ISSUE THREAD

**Issue by devbanana** [phpstan/phpstan-webmozart-assert#58]
I was surprised to see that `Assert::length($value, 26);` did not result in a non-empty-string. It seems redundant to do:

```php
Assert::stringNotEmpty($value);
Assert::length($value, 26);
```

Same goes for `Assert::minLength()`.

**Comment by ondrejmirtes** [comment]
It already works for `minLength`.

`length` assert isn't implemented yet but it's easy enough.
