### ISSUE TITLE
Assert::isNonEmptyList should result in non-empty-list

### ISSUE THREAD

**Issue by herndlm** [phpstan/phpstan-webmozart-assert#63]
Currently it results in `array`.

Example
```php
function foo(array $input) {
    Assert::isNonEmptyList($input);
    Assert::allString($input);
    \PHPStan\dumpType($input);
}

function bar(array $input) {
    Assert::isList($input);
    Assert::allString($input);
    \PHPStan\dumpType($input);
}
```

Output
```
Dumped type: array<string>
Dumped type: array<string>
```

Expected output
```
Dumped type: non-empty-list<string>
Dumped type: list<string>
```

I guess the list type in general is not implemented here.

**Comment by ondrejmirtes** [comment]
List type isn't yet recognized and supported by PHPStan.

**Comment by herndlm** [comment]
Ups, I thought this is something I can contribute.. Wasn't aware of that as it supports  it already via phpdoc :)

**Comment by ondrejmirtes** [comment]
Yeah but it's currently interpreted as array<int, X>, which you can verify with \PHPStan\dumpType().

It's useful to keep this open once the full support lands.
