### ISSUE TITLE
Tag 0.11 does not have the fix for integrish values

### ISSUE THREAD

**Issue by juntereiner** [phpstan/phpstan-webmozart-assert#9]
Hello,
I found out that the release 0.11 does not have this commit https://github.com/phpstan/phpstan-webmozart-assert/commit/a5d6fa70732b5628e64b0a4552ac0c05264cabec 

Considering the tag is 1 month younger than this commit, is there any reason for that ?

Thanks.

**Comment by ondrejmirtes** [comment]
The PR #5 was merged 12 days ago, 0.11 was released on January 16th.
